spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?createDatabaseIfNotExist=true
    username: root
    password: Coz171033!@#
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: task
